//serach
export const SEARCH_TUTOR = 'SEARCH_TUTOR'
export const SEACH_TUTOR_FUFILLED= 'SEACH_TUTOR_FUFILLED'
export const SEARCH_TUTOR_FAILED = 'SEARCH_TUTOR_FAILED'
export const FETCH_TUTORS = 'FETCH_TUTORS';
export const FETCH_TUTORS_FUFILLED = 'FETCH_TUTORS_FUFILLED'
export const FETCH_TUTORS_FAILED = 'FETCH_TUTORS_FAILED'
